name: deploy scp
on: [push]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: scp to netcup
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ secrets.SSH_RSA_KEY_NETCUP }}
          source: "*.html,*.png,*.svg,*.jpg"
          target: ${{ env.DEPLOY_PATH }}
